spring:
  application:
    name: controle_semanal
  datasource:
    url: jdbc:postgresql://localhost:5432/controle-semanal
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
